build: upgrade agent-js v2 (#5274)
# Motivation

Upgrade all required dependencies to support agent-js v2.

# Changes

- Replace `new HttpAgent(options)` with an async version, because the
constructor is deprecated -
https://github.com/dfinity/agent-js/releases.
- Upgrade `ic-js` to the upgraded to the agent-js v2 version.

# Tests

- Manually; demo link -
https://qsgjb-riaaa-aaaaa-aaaga-cai.mstr-ingress.devenv.dfinity.network/
- Because of the broken tests added mocking of the createAgent function
from the `@dfinity/utils`. This is done to avoid `agent-js` to make a
real network requests. In version 2.0, `agent-js` starts syncing time
with the replica immediately after creation, which breaks some tests
since real fetch requests are not allowed.

**Error sample:**
```
   ❯ src/tests/lib/worker-api/canisters.worker-api.spec.ts > canisters-worker-api > queryCanisterDetails > should call IC Management Canister with canister id
     → Your test produced console logs, which is not allowed.
If you need console output, mock and expect it in your test.
This failure only happens after your test finishes so if your test had other failures, you can still see them and just ignore this.
If this is only for debugging, call allowLoggingInOneTestForDebugging() from $tests/utils/console.test-utils in your test.
stderr | src/tests/lib/worker-api/canisters.worker-api.spec.ts > canisters-worker-api > queryCanisterDetails > should call IC Management Canister with canister id
It looks like the agent is trying to make a request that should have been mocked at Error:
    at Object.transformRequest (/Users/mstr/projects/nns-dapp-tree-a/frontend/src/tests/mocks/auth.store.mock.ts:16:5)
    at HttpAgent.createReadStateRequest (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:954:11)
    at HttpAgent.readState (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:962:31)
    at /Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/canisterStatus/index.ts:152:12
    at async Promise.all (index 0)
    at Module.request (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/canisterStatus/index.ts:260:3)
    at HttpAgent.syncTime (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:1029:15)
    at async Promise.all (index 0)
    at Function.create (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:372:5)
    at Module.tt (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/utils/dist/esm/index.js:4:2612)
  Expected to find result for path time, but instead found nothing.
  Error: Not implemented
      at Object.transformRequest (/Users/mstr/projects/nns-dapp-tree-a/frontend/src/tests/mocks/auth.store.mock.ts:18:9)
      at HttpAgent.createReadStateRequest (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:954:11)
      at HttpAgent.readState (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:962:31)
      at /Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/canisterStatus/index.ts:152:12
      at async Promise.all (index 0)
      at Module.request (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/canisterStatus/index.ts:260:3)
      at HttpAgent.syncTime (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:1029:15)
      at async Promise.all (index 0)
      at Function.create (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/agent/src/agent/http/index.ts:372:5)
      at Module.tt (/Users/mstr/projects/nns-dapp-tree-a/frontend/node_modules/@dfinity/utils/dist/esm/index.js:4:2612)
```

# Todos

- [x] Add entry to changelog (if necessary).

---------

Co-authored-by: Max Strasinsky <maksims.strasinskis@dfinity.org>
Co-authored-by: Max Strasinsky <98811342+mstrasinskis@users.noreply.github.com>