Fail on cargo audit error (#6411)
# Motivation

`release-sop` assumes that `cargo audit --json` will either
* succeed and not output any issues, or
* fail and output issues

But `cargo audit` has been failing without outputting anything on
stdout, and the following error on stderr:
```
error: not found: Couldn't load Cargo.lock: I/O operation failed: parse error: parse error: invalid Cargo.lock format version: `4`
```
This went unnoticed because the `release-sop` script assumed success
because there was no output on stdout.

# Changes

1. Only assume there are no vulnerabilities if `cargo audit` succeeds.

# Tests

1. Manually ran the command on an old commit without issues, on an old
commit with issues and on a new commit with the above error.

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary