fix: canisters mgmt calls failing with aaaaa-aa not in ranges field (#7321)
# Motivation

The Canister mgmt features are broken in NNS dapp on mainnet.

> TrustError: The certificate contains a delegation that does not
include the canister aaaaa-aa in the canister_ranges field. Subnet ID:
6pbhf-qzpdk-kuqbr-pklfa-5ehhf-jfjps-zsj6q-57nrl-kzhpd-mu7hc-vae

Root cause of the issue is an issue in AgentJS that was patched in
`v3.2.4` (released in monorepo
[v4.0.2](https://github.com/dfinity/icp-js-core/releases/tag/v4.0.2)).

# Screenshots of the errors

<img width="3072" height="2062" alt="image"
src="https://github.com/user-attachments/assets/756c99ef-0fa6-47bb-9cf7-8dbab61aacd6"
/>

<img width="3072" height="2062" alt="image"
src="https://github.com/user-attachments/assets/bb6700be-b5ae-46ef-9fa5-97e15636a352"
/>

# Changes

- Bump AgentJS to latest version

# Tests

I can reproduce the issue with a NodeJS script that uses
`@dfinity/ic-management`.

```
#!/usr/bin/env node

import { getIdentity } from "./auth.mjs";
import { ICManagementCanister } from "@dfinity/ic-management";
import { createAgent } from "@dfinity/utils";
import { Principal } from "@dfinity/principal";

const identity = await getIdentity();

const satelliteId = process.env.JUNO_SATELLITE_ID;

const agent = await createAgent({
  identity,
});

const { canisterStatus } = ICManagementCanister.create({
  agent,
});

const { status } = await canisterStatus(Principal.fromText(satelliteId));

console.log(status);
```

Upgrading AgentJS in this example resolved the issue.

Signed-off-by: David Dal Busco <david.dalbusco@dfinity.org>