Allow histogram API calls only as query calls (#3373)
# Motivation
The histogram API method is intended only for analysis and may be
removed at any time, so should not be called by other canisters. To
ensure that other canisters do not use this method, we block non-query
calls.

# Changes
- Prevent calls to `get_histogram()` that have a data certificate, such
as update calls but not query calls.

# Tests
Build and deploy:
```
max@sinkpad:~/dfn/nns-dapp/branches/no-update-histogram (1:38)$ ./scripts/docker-build --network local
max@sinkpad:~/dfn/nns-dapp/branches/no-update-histogram (1:52)$ dfx canister install nns-dapp --wasm ./out/nns-dapp_production.wasm.gz --argument "$(cat ./out/nns-dapp-arg-local.did )"
Installing code for canister nns-dapp, with canister ID bkyz2-fmaaa-aaaaa-qaaaq-cai
```
Test:
```
max@sinkpad:~/dfn/nns-dapp/branches/no-update-histogram (9:58)$ dfx canister call nns-dapp get_histogram --query
(
  record {
    sub_account_transactions = vec {};
    accounts_count = 0 : nat64;
    canisters = vec {};
    hardware_wallet_accounts = vec {};
    default_account_transactions = vec {};
    sub_accounts = vec {};
  },
)
max@sinkpad:~/dfn/nns-dapp/branches/no-update-histogram (10:02)$ dfx canister call nns-dapp get_histogram --update
Error: Failed update call.
Caused by: Failed update call.
  The Replica returned an error: code 5, message: "Canister bkyz2-fmaaa-aaaaa-qaaaq-cai trapped explicitly: Sorry, the histogram is available only as a query call."
```

# Todos

- [x] Add entry to changelog (if necessary).

---------

Co-authored-by: Max Murphy <max@winning.black>