Update rust version to 1.80.0 (#5243)
# Motivation

The [bot PR](https://github.com/dfinity/nns-dapp/pull/5241) failed
because the new rust version has stricter linting.
```
error: doc list item missing indentation
  --> rs/proposals/src/canisters/nns_governance/internal.rs:12:5
   |
12 | /// The public type is probably better.  Maybe we can ask upstream to use the public type?
   |     ^
   |
   = help: if this is supposed to be its own paragraph, add a blank line
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#doc_lazy_continuation
   = note: `-D clippy::doc-lazy-continuation` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::doc_lazy_continuation)]`
help: indent this line
   |
12 | ///    The public type is probably better.  Maybe we can ask upstream to use the public type?
   |     +++
```

# Changes

1. Update rust to 1.80.0
2. Add a blank line in a comment to satisfy the linter.

# Tests

Lint passes.

# Todos

- [ ] Add entry to changelog (if necessary).
not necessary