Remove unused pocket-ic dependency (#5461)
# Motivation

Reduce maintenance burden by removing unused dependencies.
The pocket-ic dependency is currently not being used.

# Changes

1. Remove `pocket-ic` dependency from `rs/backend/Cargo.toml`.
2. Add `"full"` features for `tokio` because without it I get
`error[E0433]: failed to resolve: could not find `test` in `tokio``.
3. Ran `cargo update`.
4. Remove `pocket-ic` setup from `scripts/setup`.

# Tests

CI passes.

# Todos

- [x] Add entry to changelog (if necessary).